repos:
  - repo: local
    hooks:
      - id: pylint
        args: [--ignore=version.py]
        name: pylint
        entry: .tox/pre-commit/bin/pylint
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: yapf
        args: [--in-place]
        name: yapf
        entry: .tox/pre-commit/bin/yapf
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: .tox/pre-commit/bin/pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
